---
- name: Update apt packages
  apt:
    update_cache: yes


- name: Install apt packages
  apt:
    name:
      - docker
      - docker-compose
      - git
      - python3
      - python3-pip
    update_cache: yes



