# Generated by Django 3.1.14 on 2022-03-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_book_app', '0003_book_isbn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_year',
            new_name='pubYear',
        ),
    ]
