# Generated by Django 3.1.14 on 2022-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_book_app', '0004_auto_20220321_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='book',
            name='pubYear',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4),
        ),
    ]
